name: pinn-jd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.1.0=gpu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=1.3.0=py37h06a4308_0
  - aiohttp=3.8.3=py37h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astor=0.8.1=py37h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py37h06a4308_0
  - asynctest=0.13.0=py_0
  - attrs=22.1.0=py37h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37h06a4308_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - fftw=3.3.10=hbd630f4_0
  - flatbuffers=25.2.10=h6a678d5_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - frozenlist=1.3.3=py37h5eee18b_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h5eee18b_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.46.1=h33aed49_1
  - grpcio=1.42.0=py37hce63b2e_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py37h06a4308_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9f=h5ce9db8_0
  - keras=2.4.3=hd3eb1b0_0
  - keras-base=2.4.3=pyhd3eb1b0_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libcurl=8.2.1=h91b91d3_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - markdown=3.4.1=py37h06a4308_0
  - markupsafe=2.1.1=py37h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - multidict=6.0.2=py37h5eee18b_0
  - ncurses=6.5=h7934f7d_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - oauthlib=3.2.1=py37h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=22.0=py37h06a4308_0
  - pip=22.3.1=py37h06a4308_0
  - protobuf=3.20.3=py37h6a678d5_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py37h06a4308_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h7a1cb2a_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - pyyaml=6.0=py37h5eee18b_1
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - requests=2.28.1=py37h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.7.3=py37h6c91a56_2
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.0=h2a70700_0
  - tensorboard=2.10.0=py37h06a4308_0
  - tensorboard-data-server=0.6.1=py37h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py37h06a4308_0
  - tensorflow=2.4.1=gpu_py37ha2e99fa_0
  - tensorflow-base=2.4.1=gpu_py37h29c2da4_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - tensorflow-gpu=2.4.1=h30adc30_0
  - termcolor=2.1.0=py37h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - urllib3=1.26.14=py37h06a4308_0
  - werkzeug=2.2.2=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - wrapt=1.14.1=py37h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py37h5eee18b_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - cmcrameri==1.9
      - cycler==0.11.0
      - dill==0.3.7
      - fonttools==4.38.0
      - kiwisolver==1.4.5
      - matplotlib==3.5.3
      - multiprocess==0.70.15
      - pandas==1.3.5
      - pathos==0.3.1
      - pillow==9.5.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - psutil==7.1.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - salib==1.4.5
prefix: /mnt/Home-Group/jbohorquez_cps/miniconda3/envs/pinn-jd